### ISSUE TITLE
这里有个空指针异常

### ISSUE THREAD

**Issue by peteryyx** [maning0303/MNProgressHUD#14]
java.lang.NullPointerException: Attempt to read from field 'int com.maning.mndialoglibrary.MProgressBarDialog$Builder.style' on a null object reference
	at com.maning.mndialoglibrary.MProgressBarDialog.showProgress(MProgressBarDialog.java:190)
	at com.maning.mndialoglibrary.MProgressBarDialog.showProgress(MProgressBarDialog.java:174)
	at package name.BackUpActivity$11.onProgress(BackUpActivity.java:1070)
	at me.jessyan.progressmanager.body.ProgressResponseBody$1$1.run(ProgressResponseBody.java:119)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
这个问题碰到过几次 有时showProgress的时候就会出现

**Comment by maning0303** [comment]
@peteryyx 你可以看看最新版本，做了一些判空处理对这个地方。谢谢反馈。
