### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by liuwenzhi1** [maning0303/MNProgressHUD#8]
快速点击的时候出现了  
java.lang.NullPointerException: Attempt to read from field 'int com.maning.mndialoglibrary.config.MDialogConfig.animationID' on a null object reference
        at com.maning.mndialoglibrary.MProgressDialog.configView(MProgressDialog.java:81)
        at com.maning.mndialoglibrary.MProgressDialog.initDialog(MProgressDialog.java:66)
        at com.maning.mndialoglibrary.MProgressDialog.showProgress(MProgressDialog.java:120)
        at com.maning.mndialoglibrary.MProgressDialog.showProgress(MProgressDialog.java:106)
        atxxxxxxx.onClick(RankActivity.java:277)
        at xxxxx_ViewBinding$1.doClick(RankActivity_ViewBinding.java:45)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:4809)
        at android.view.View$PerformClick.run(View.java:20006)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5321)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by maning0303** [comment]
@liuwenzhi1 感谢反馈，只有快速点击才会出现吗？ 正常点击呢？

**Comment by liuwenzhi1** [comment]
正常点击不会 我增加了时间判断就没有问题了

**Comment by liuwenzhi1** [comment]
@maning0303  正常点击不会 然后我增加了一个点击时间判断就好了

**Comment by maning0303** [comment]
@liuwenzhi1 我更新了新版V1.1.0,你要是有时间可以试试新版快速点击会不会出现，我这边不会出现，麻烦了。感谢

**Comment by liuwenzhi1** [comment]
@maning0303  感谢 我等下更新试试看
