### ISSUE TITLE
在上一个progress还没关闭之前又打开一个progress的话，会报错

### ISSUE THREAD

**Issue by tank21** [maning0303/MNProgressHUD#9]
Process: com.maning.mnprogressdialog, PID: 29915
    java.lang.NullPointerException: Attempt to read from field 'int com.maning.mndialoglibrary.config.MDialogConfig.animationID' on a null object reference
        at com.maning.mndialoglibrary.MProgressDialog.configView(MProgressDialog.java:82)
        at com.maning.mndialoglibrary.MProgressDialog.initDialog(MProgressDialog.java:67)
        at com.maning.mndialoglibrary.MProgressDialog.showProgress(MProgressDialog.java:157)
        at com.maning.mndialoglibrary.MProgressDialog.showProgress(MProgressDialog.java:139)
        at com.maning.mnprogressdialog.MainActivity$2.run(MainActivity.java:211)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by tank21** [comment]
希望这个地方可以改进下

**Comment by maning0303** [comment]
@tank21 谢谢你的反馈，最新版本已经提交，你试试最新版本，我这边测试progress没有关闭再打开是OK的，我怀疑可能是另外的原因导致空或者动画设置错误空指针。你先试试最新版本，还有问题在联系我。谢谢。
